name: Slither Analysis
on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - /^feature.*/
      - /^hotfix.*/
      - /^fix.*/
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.2.0
        with:
          fail-on: medium
          node-version: 18
